version: '3.8'

services:
  classdojo-debit-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classdojo-debit-system
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=change-this-secret-key-in-production
    volumes:
      - ./database:/app/database
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health').read()"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

volumes:
  database:
    driver: local
