apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: classdojo-pvc
  namespace: classdojo-system
  labels:
    app: classdojo-debit-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
