apiVersion: v1
kind: PersistentVolume
metadata:
  name: classdojo-pv
  labels:
    app: classdojo-debit-system
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/classdojo-db"
    type: DirectoryOrCreate
