apiVersion: v1
kind: Secret
metadata:
  name: classdojo-secret
  namespace: classdojo-system
  labels:
    app: classdojo-debit-system
type: Opaque
stringData:
  # IMPORTANT: Change this secret key before deploying to production!
  # Generate a secure key using: python -c "import secrets; print(secrets.token_hex(32))"
  SECRET_KEY: "change-this-to-a-secure-random-key-in-production"
